# email 配置, 功能被废弃了   
mail:
  to: example@example.net
  host: smtp.example.com 
  from:
    address: example@example.net
    password: password 
    
# 登入的帐号密码  
ssfblog:
  username: yourusername
  password: password 
  title: My Blog
  myName: My Name
  slogan: My slogan
  photo: ./1.jpg
  myEmail: xxx@xxx.xxx
  twitter: 
  facebook: https://www.facebook.com/xxxxxxxxxxxxxxxxx
  github: https://github.com/tenie
  weixin:  
  beianNo: ICP备xxxxxxxxx号-1
  Copyright: xxx.xxx 2222
  aboutMe:
    title: 关于blog
    head1: head1 xxxx
    text1: text1 xxxx
    head2: head1 xxxx
    text2: text2 xxxx
  

server:
  port: 8088
#  servlet:
#    context-path: /demo
spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/./ssfblog_db
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
    continue-on-error: true
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
  freemarker:
    suffix: .ftl
    cache: false
    charset: UTF-8
    settings:
      template_exception_handler: net.tenie.myblog.config.FreemarkerExceptionHandler
      datetime_format: yyyy-MM-dd HH:mm:ss
      time_format: HH:mm:ss
      number_format: 0.####
      boolean_format: true,false
logging:
  level:
     net.tenie.myblog : debug   
mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
    jdbc-type-for-null:  'null'
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: net.tenie.myblog.entity

  
 